/*
Time waste API

Testing DefaultAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_DefaultAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DefaultAPIService ActivitiesMillisecondsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var milliseconds int32

		resp, httpRes, err := apiClient.DefaultAPI.ActivitiesMillisecondsGet(context.Background(), milliseconds).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DefaultAPIService ActivityMillisecondsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var milliseconds int32

		resp, httpRes, err := apiClient.DefaultAPI.ActivityMillisecondsGet(context.Background(), milliseconds).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
