services:
  web:
    build:
      dockerfile: ./build/Dockerfile
    ports:
      - "5555:5555"
  db:
    image: "postgres:17.2-alpine3.20"
    restart: "always"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5431:5432"
